"""add_2fa_and_lockout_fields_to_user

Revision ID: 3584487f8c36
Revises: 51320de64fff
Create Date: 2026-04-27 23:10:55.640841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3584487f8c36'
down_revision = '51320de64fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
