"""remove is_email_verified and progress columns

Revision ID: 51320de64fff
Revises: df20c0834791
Create Date: 2026-04-12 02:16:03.162443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51320de64fff'
down_revision = 'df20c0834791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('progress')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
