"""add ai_metadata to tasks

Revision ID: 6bcfff8e64eb
Revises: f3ef3d3b5fae
Create Date: 2026-05-07 03:28:07.951849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcfff8e64eb'
down_revision = 'f3ef3d3b5fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_delay_risk', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_skills', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('ai_skills')
        batch_op.drop_column('ai_delay_risk')
        batch_op.drop_column('ai_difficulty')
        batch_op.drop_column('ai_category')

    # ### end Alembic commands ###
