"""add extended profile fields and notifications table

Revision ID: df20c0834791
Revises: 20d87dcc3ce2
Create Date: 2026-04-12 01:42:59.655153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df20c0834791'
down_revision = '20d87dcc3ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_field', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_level', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('looking_for_team', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reason_for_joining', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reason_for_joining')
        batch_op.drop_column('looking_for_team')
        batch_op.drop_column('major')
        batch_op.drop_column('current_level')
        batch_op.drop_column('skills')
        batch_op.drop_column('availability')
        batch_op.drop_column('experience_level')
        batch_op.drop_column('professional_field')

    # ### end Alembic commands ###
