"""add account_status github_id disputes table

Revision ID: f3ef3d3b5fae
Revises: 3584487f8c36
Create Date: 2026-05-04 21:27:42.696393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ef3d3b5fae'
down_revision = '3584487f8c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_status', sa.String(length=20), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('account_status_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['github_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('github_id')
        batch_op.drop_column('account_status_note')
        batch_op.drop_column('account_status')

    # ### end Alembic commands ###
