[build]
  base    = "teamify_flutter"
  command = "bash ./netlify-build.sh"
  publish = "build/web"

[build.environment]
  GIT_SUBMODULE_STRATEGY = "none"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
